### ISSUE TITLE
Server error with Node v18.4

### ISSUE THREAD

**Issue by durw4rd** [tanben/sample-nextjs#1]
When I initially tried running the app locally with Node v18.4, I got a 500 server error when requesting the app in the browser. Similar to what's discussed here: https://github.com/vercel/next.js/issues/49677
After switching to Node v16.8 it works fine - it may be worth calling out in the Readme instructions that the newer Node versions can give problems.

**Comment by tanben** [comment]
Thank you for looking into this I've made the update based on your findings.
